-- Migration: DO NOT add unique constraint on user_point_history
-- 
-- IMPORTANT: This migration was originally intended to prevent duplicate point awards,
-- but after review, it was determined that users CAN receive points for the same step
-- multiple times because:
--
-- 1. Users can REJOIN tasks after unjoining
-- 2. When a user unjoins, their point history for that task is cleaned up
-- 3. When they rejoin and complete steps again, they should earn points again
--
-- Therefore, NO unique constraint should be added to user_point_history.
-- The application logic handles duplicate prevention within the same enrollment session.
--
-- This file is kept for documentation purposes only.
-- NO CHANGES TO APPLY.
